spec:
  inputs:
    webhook-url:
      description: "The webhook URL to send Notification"
      type: string
    status:
      description: "Status of the pipeline (e.g., success, failure)."
      type: string
    message:
      description: "Main message for the notification."
      type: string
    project:
      description: "Project name."
      type: string
    branch:
      description: "Branch name (e.g., main, develop)."
      type: string
    repository:
      description: "Repository name (owner/repo)."
      type: string
    commit:
      description: "Commit SHA."
      type: string
    cloud-provider:
      description: "Cloud provider information."
      type: string
    user:
      description: "User who triggered the workflow."
      type: string
    build-url:
      description: "URL to the pipeline run."
      type: string
    # Vulnerability Docker Image Counts (optional)
    critical-count:
      description: "Number of critical vulnerabilities."
      type: string
      default: ""
    high-count:
      description: "Number of high vulnerabilities."
      type: string
      default: ""
    medium-count:
      description: "Number of medium vulnerabilities."
      type: string
      default: ""
    low-count:
      description: "Number of low vulnerabilities."
      type: string
      default: ""
    unknown-count:
      description: "Number of unknown vulnerabilities."
      type: string
      default: ""
    total-count:
      description: "Total number of vulnerabilities."
      type: string
      default: ""
---

stages:
- notify

.notify:
  stage: notify
  image: alpine:latest
  before_script:
  - apk add --no-cache curl jq
  script:
  - |
    bash scripts/send-trigger.sh \
          "$[[ inputs.status ]]" \
          "$[[ inputs.message ]]" \
          "$[[ inputs.project ]]" \
          "$[[ inputs.branch ]]" \
          "$[[ inputs.repository ]]" \
          "$[[ inputs.commit ]]" \
          "$[[ inputs.cloud-provider ]]" \
          "$[[ inputs.user ]]" \
          "$[[ inputs.build-url ]]" \
          "$[[ inputs.critical-count ]]" \
          "$[[ inputs.high-count ]]" \
          "$[[ inputs.medium-count ]]" \
          "$[[ inputs.low-count ]]" \
          "$[[ inputs.unknown-count ]]" \
          "$[[ inputs.total-count ]]" \
          "$[[ inputs.webhook-url ]]"
