stages:
- notify

.notify:
  stage: notify
  image: alpine:latest
  before_script:
  - apk add --no-cache curl jq
  - source variables.env
  script:
  - |
    curl -s https://raw.githubusercontent.com/Tooark/notification-trigger-url-include/main/scripts/send-trigger.sh | sh -s \
          "$NOTIFICATION_STATUS" \
          "$CI_COMMIT_MESSAGE" \
          "$CI_PROJECT_NAME" \
          "$CI_COMMIT_BRANCH" \
          "$CI_REPOSITORY_URL" \
          "$CI_COMMIT_SHORT_SHA" \
          "$CLOUD_PROVIDER" \
          "$GITLAB_USER_NAME" \
          "$CI_PIPELINE_URL" \
          "$CRITICAL_COUNT" \
          "$HIGH_COUNT" \
          "$MEDIUM_COUNT" \
          "$LOW_COUNT" \
          "$UNKNOWN_COUNT" \
          "$TOTAL_COUNT" \
          "$NOTIFY_WEBHOOK_URL"
