spec:
  inputs:
    webhook_url:
      description: "The webhook URL to send Notification"
      type: string
    message:
      description: "Main message for the notification."
      type: string
    project:
      description: "Project name."
      type: string
    branch:
      description: "Branch name (e.g., main, develop)."
      type: string
    repository:
      description: "Repository name (owner/repo)."
      type: string
    commit:
      description: "Commit SHA."
      type: string
    cloud_provider:
      description: "Cloud provider information."
      type: string
    user:
      description: "User who triggered the workflow."
      type: string
    build_url:
      description: "URL to the pipeline run."
      type: string
    # Vulnerability Docker Image Counts (optional)
    critical_count:
      description: "Number of critical vulnerabilities."
      type: string
      default: ""
    high_count:
      description: "Number of high vulnerabilities."
      type: string
      default: ""
    medium_count:
      description: "Number of medium vulnerabilities."
      type: string
      default: ""
    low_count:
      description: "Number of low vulnerabilities."
      type: string
      default: ""
    unknown_count:
      description: "Number of unknown vulnerabilities."
      type: string
      default: ""
    total_count:
      description: "Total number of vulnerabilities."
      type: string
      default: ""
---

stages:
- notify

.notify:
  stage: notify
  image: alpine:latest
  before_script:
  - apk add --no-cache curl jq
  script:
  - |
    curl -s https://raw.githubusercontent.com/Tooark/notification-trigger-url-include/main/scripts/send-trigger.sh | sh -s \
          "$NOTIFICATION_STATUS" \
          "$[[ inputs.message ]]" \
          "$[[ inputs.project ]]" \
          "$[[ inputs.branch ]]" \
          "$[[ inputs.repository ]]" \
          "$[[ inputs.commit ]]" \
          "$[[ inputs.cloud_provider ]]" \
          "$[[ inputs.user ]]" \
          "$[[ inputs.build_url ]]" \
          "$[[ inputs.critical_count ]]" \
          "$[[ inputs.high_count ]]" \
          "$[[ inputs.medium_count ]]" \
          "$[[ inputs.low_count ]]" \
          "$[[ inputs.unknown_count ]]" \
          "$[[ inputs.total_count ]]" \
          "$[[ inputs.webhook_url ]]"
